// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestPozytywnyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testPozytywny() {
    driver.get("https://dev-1.clicktrans.pl/register-test/courier");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.id("user_register_company_name")).click();
    driver.findElement(By.id("user_register_company_name")).sendKeys("Nazwa Firmy");
    driver.findElement(By.id("user_register_email")).sendKeys("Tester@mail.com");
    driver.findElement(By.id("user_register_name")).sendKeys("Imię Nazwisko");
    driver.findElement(By.id("user_register_phoneCode")).click();
    {
      WebElement dropdown = driver.findElement(By.id("user_register_phoneCode"));
      dropdown.findElement(By.xpath("//option[. = '(+687) Nowa Kaledonia']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(149)")).click();
    driver.findElement(By.id("user_register_phone")).click();
    driver.findElement(By.id("user_register_phone")).sendKeys("123456789");
    driver.findElement(By.id("user_register_plainPassword")).click();
    driver.findElement(By.id("user_register_plainPassword")).sendKeys("12345678");
    driver.findElement(By.id("ct-registration-agreements")).click();
    driver.findElement(By.id("user_register_settings_agreementRegulations")).click();
    driver.findElement(By.id("user_register_settings_agreementPersonalData")).click();
    driver.findElement(By.id("user_register_submit")).click();
  }
}
